# Generated by Django 5.1.1 on 2024-11-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allowed_Seller',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('seller_username', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender_id', models.IntegerField()),
                ('position_id', models.IntegerField()),
                ('cat_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('seller_username', models.TextField()),
                ('cat_id', models.IntegerField()),
                ('image_path', models.TextField()),
                ('description', models.TextField()),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
