# Generated by Django 5.1.1 on 2024-11-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowed_seller',
            name='seller_username',
            field=models.TextField(null=True),
        ),
    ]
