# Generated by Django 5.1.1 on 2024-11-19 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_allowed_seller_seller_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowed_seller',
            name='phone_number',
            field=models.TextField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allowed_seller',
            name='starting_date',
            field=models.DateField(default=datetime.date(2024, 11, 19)),
            preserve_default=False,
        ),
    ]
