# Generated by Django 5.1.1 on 2024-11-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_allowed_seller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowed_seller',
            name='seller_username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
